[package]
name = "moedit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cozo = "0.7.5"
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
termion = "2.0.3"
